config/routes.rb
Rails.application.routes.draw do

  resources :klasses do
    resources :standards do
      resources :students do
        get 'attendances/index'
        resources :exams
      end
    end
  end

  root 'klasses#index'

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id           :integer          not null, primary key
#  name         :string
#  fathers_name :string
#  gender       :integer
#  dob          :date
#  phone        :string
#  address      :text
#  standard_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Student < ActiveRecord::Base
  belongs_to :standard
  has_many :attendance
  has_many :exam

  validates(:name, presence: true)
  validates(:address, presence: true)
  validates(:standard_id, presence: true)
  # validates(:gender, presence: true)
  validates(:dob, presence: true)
  validates(:fathers_name, presence: true)
  # validates(:phone, presence: true)


end

app/controllers/students_controller.rb
# == Schema Information
#
# Table name: students
#
#  id           :integer          not null, primary key
#  name         :string
#  fathers_name :string
#  gender       :integer
#  dob          :date
#  phone        :string
#  address      :text
#  standard_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class StudentsController < ApplicationController
  before_action :fetch_standard

  def index
    @students = @standard.students.all
  end

  def new 
    @student = @standard.students.new    
  end

  def create
    @student = @standard.students.new(student_params)
    if @student.save
      flash[:success] = "Successfully added a standard."
      redirect_to klass_standard_students_path
    else 
      flash[:error] = "Successfully added a standard."
      render :new
    end
  end

  def edit
    @student = @standard.students.find(params[:id])
  end

  def update
    @student = @standard.students.find(params[:id])
    @student.update_attributes(student_params)
    redirect_to klass_standard_students_path
  end

  def show
    @student = @standard.students.find(params[:id])
  end

  def destroy
    @student = @standard.students.find(params[:id])
    @student.destroy!
    redirect_to klass_standard_students_path
  end

  private
  def fetch_standard
    @klass = Klass.find(params[:klass_id])
    @standard = @klass.standards.find(params[:standard_id])
  end

  def student_params
    params.require(:student).permit(:name, :fathers_name, :gender, :address, :phone, :dob)
  end
end

app/helpers/students_helper.rb
# == Schema Information
#
# Table name: students
#
#  id           :integer          not null, primary key
#  name         :string
#  fathers_name :string
#  gender       :integer
#  dob          :date
#  phone        :string
#  address      :text
#  standard_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

module StudentsHelper
end

app/views/students/edit.html.erb
<div class="container">
  <h1>Edit your standard name</h1>
  <%= simple_form_for [@klass, @standard, @student] do |f| %>
  <%= f.input :name %>
  <%= f.input :standard_id, collection: Standard.all, value_method: :id %>
  <%= f.input :address, required: true %>
  <%= f.input :dob, as: :date, start_year: Date.today.year - 50,
  end_year: Date.today.year - 2, discard_day: false, order: [:day, :month, :year], required: true %>
  <%= f.input :fathers_name, required: true %>
  <%= f.submit "Change Details", class: "btn btn-default" %>
  <%= link_to "Cancel", :back, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/students/index.html.erb
<div class="container">

  <h1>Students</h1>
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Student ID</th>
        <th>Name</th>
        <!-- <th>Standard Name</th> -->
        <th>Date of Birth</th>
        <th>Date</th>
        <th>Attendance</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td><%= link_to student.name, klass_standard_student_exams_path(@klass, @standard, student) %></td>
        <!-- <td><%= student.standard.name %></td> -->
        <td><%= student.dob %></td>
        <td><%= Date.current().readable_inspect() %></td>
        <td><label class="checkbox-inline">
          <input type="checkbox" id="inlineCheckbox1" value="option1"> 1
          </label> 
        </td>
        <td><%= link_to "Delete", klass_standard_student_path(@klass, @standard, student), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %></td>
        <td><%= link_to "Edit", edit_klass_standard_student_path(@klass, @standard, student), class: "btn btn-default" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% if params[:standard_id] %>
    <%= link_to "Add New Student", new_klass_standard_student_path, class: "btn btn-primary" %>
    <%= link_to "Back", :back, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Add New Student", new_klass_standard_student_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/students/new.html.erb
<div class="container">
  <h1>Add new Student</h1>
  <%= simple_form_for [@klass, @standard, @student] do |f|%>
    <%= f.input :name, required: true %>
    <%= f.input :address, required: true %>
    <%= f.input :standard_id, collection: Standard.all, value_method: :id %>
    <%= f.input :dob, as: :date, html5: true, required: true %>
    <%= f.input :fathers_name, label: "Father's Name", required: true %>
    <%= f.submit "Add New Student", class: "btn btn-primary" %>
    <%= link_to "Cancel", klass_standard_students_path, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/students/show.html.erb
<h2>Exams</h2>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading text-center">Final Exam</div>

  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        <th>Subject Name</th>
        <th>Marks</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Maths</td>
        <td>90</td>
      </tr>
      <tr>
        <td>English</td>
        <td></td>
      </tr>
      <tr>
        <td>Science</td>
        <td></td>
      </tr>
      <tr>
        <td>Hindi</td>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>