config/routes.rb
Rails.application.routes.draw do

  resources :klasses do
    resources :standards do
      resources :students do
        get 'attendances/index'
        resources :exams
      end
    end
  end

  root 'klasses#index'

end

app/models/standard.rb
# == Schema Information
#
# Table name: standards
#
#  id         :integer          not null, primary key
#  name       :string
#  klass_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Standard < ActiveRecord::Base
  belongs_to :klass
  has_many :students

  validates(:name, presence: true)
end

app/controllers/standards_controller.rb
# == Schema Information
#
# Table name: standards
#
#  id         :integer          not null, primary key
#  name       :string
#  klass_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class StandardsController < ApplicationController
  before_action :fetch_klass

  def index
    @standards = @klass.standards.all
  end

  def new
    @standard = @klass.standards.new
  end

  def create
    @standard = @klass.standards.new(standard_params)
    if @standard.save
      flash[:success] = "Successfully added a standard."
      redirect_to klass_standards_path
    else
      flash[:error] = "Oops! Looks like you forgot to add a standard level."
      render :new
    end
  end

  def edit
    @standard = Standard.find(params[:id])
  end

  def update
    @standard = Standard.find(params[:id])
    @standard.update_attributes(standard_params)
    redirect_to klass_standards_path
  end

  def destroy
    @standard = Standard.find(params[:id])
    @standard.destroy!
    redirect_to klass_standards_path
  end

  private
  def standard_params
    params.require(:standard).permit(:name)
  end
  def fetch_klass
    @klass = Klass.find(params[:klass_id])
  end
end

app/helpers/standards_helper.rb
# == Schema Information
#
# Table name: standards
#
#  id         :integer          not null, primary key
#  name       :string
#  klass_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module StandardsHelper
end

app/views/standards/edit.html.erb
<div class="container">
  <h1>Edit your standard name</h1>
  <%= simple_form_for @standard do |f| %>
  <%= f.input :name %>
  <%= f.submit "Change Name", class: "btn btn-primary" %>
  <%= link_to "Cancel", :back, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/standards/index.html.erb
<div class="container">
<h1>Standards</h1>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Level</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @standards.each do |standard| %>
    <tr>
      <td><%= link_to standard.name, klass_standard_students_path(standard_id: standard.id) %></td>
      <td><%= link_to "Edit", edit_klass_standard_path(@klass, standard), class: "btn btn-default" %></td>
      <td><%= link_to "Delete", klass_standard_path(@klass, standard), class: "btn btn-default", method: :delete, data: {confirm: "Are you sure?"} %></td>
      <td><%= link_to "Attendance", klass_standard_student_attendances_index_path(@klass, standard, :student_id), class: "btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add New Standard", new_klass_standard_path(@klass), class: "btn btn-primary" %>
</div>

app/views/standards/new.html.erb
<div class="container">
  <h1>Add New Standard</h1>
  <%= simple_form_for [@klass, @standard] do |f|%>
  <%= f.input :name, required: true %>
  <%= f.submit "Add New Standard", class: "btn btn-primary" %>
  <%= link_to "Cancel", klass_standards_path, class: "btn btn-primary" %>
  <% end %>
</div>