config/routes.rb
Rails.application.routes.draw do

  resources :klasses do
    resources :standards do
      resources :students do
        get 'attendances/index'
        resources :exams
      end
    end
  end

  root 'klasses#index'

end

app/models/exam.rb
# == Schema Information
#
# Table name: exams
#
#  id           :integer          not null, primary key
#  subject_name :string
#  marks        :integer
#  total        :integer
#  student_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Exam < ActiveRecord::Base
  belongs_to :student
end

app/controllers/exams_controller.rb
# == Schema Information
#
# Table name: exams
#
#  id           :integer          not null, primary key
#  subject_name :string
#  marks        :integer
#  total        :integer
#  student_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ExamsController < ApplicationController
  before_action :fetch_student

  def index
    @exams = Exam.all 
  end

  def new
    @exam = Exam.new
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.save
      flash[:success] = "Successfully added exam marks"
      redirect_to klass_standard_student_exams_path
    else
      flash[:error] = "Oops, its a error"
      render :new
    end

    def show
      @exam = @student.exams.find(params[:id])
    end

    def edit
      @exam = Exam.find(params[:id])
    end

    def update
      @exam = @student.exams.find(params[:id])
      @exam.update_attributes(exam_params)
      redirect_to klass_standard_student_exams_path
    end

    def destroy
      @exam = @student.exams.find(params[:id])
      @exam.destroy!
      redirect_to klass_standard_student_exams_path
    end
  end


  private
  def exam_params
    params.require(:exam).permit(:subject_name, :marks, :total)
  end

  def fetch_student
    @klass = Klass.find(params[:klass_id])
    @standard = @klass.standards.find(params[:standard_id])
    @student = @standard.students.find(params[:student_id])
  end
end

app/helpers/exams_helper.rb
# == Schema Information
#
# Table name: exams
#
#  id           :integer          not null, primary key
#  subject_name :string
#  marks        :integer
#  total        :integer
#  student_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

module ExamsHelper
end

app/views/exams/edit.html.erb
edit.html.erb

app/views/exams/index.html.erb
<h2>Exams <% @exams.each do |exam| %>
      <%= link_to content_tag(:i, '', class: "fa fa-pencil-square fa-lg"), edit_klass_standard_student_exam_path(@klass, @standard, @student, exam) %>
    <% end %>
</h2> 

<div class="panel panel-default">
  <!-- Default panel contents -->
  <h4 class="panel-heading text-center">Final Exam </h4>
    
  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        <th>Subject Name</th>
        <th>Marks</th>
      </tr>
    </thead>
    <tbody>
      <% @exams.each do |exam| %>
        <tr>
          <td>exam.subject_name</td>
          <td>exam.marks</td>
        </tr>
        <tr>
          <td>English</td>
          <td></td>
        </tr>
        <tr>
          <td>Science</td>
          <td></td>
        </tr>
        <tr>
          <td>Hindi</td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to "Add New Exam", new_klass_standard_student_exam_path, class: "btn btn-primary" %>

app/views/exams/new.html.erb
<div class="container">
  <h1>Add Exam Marks</h1>
  <%= simple_form_for [@klass, @standard, @student, @exam] do |f|%>
    <%= f.input :subject_name, required: true %>
    <%= f.input :marks, required: true %>
    <%= f.submit "Add New Exam", class: "btn btn-primary" %>
    <%= link_to "Cancel", klass_standard_student_exams_path, class: "btn btn-primary"%>
  <% end %>
</div>