config/routes.rb
Rails.application.routes.draw do

  resources :klasses do
    resources :standards do
      resources :students do
        get 'attendances/index'
        resources :exams
      end
    end
  end

  root 'klasses#index'

end

app/controllers/klasses_controller.rb
# == Schema Information
#
# Table name: klasses
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class KlassesController < ApplicationController

  def index
    @klasses = Klass.all
  end

  def new
    @klass = Klass.new
  end 

  def update
    @klass = Klass.find(params[:id])
    @klass.update_attributes(klass_params)
    redirect_to klasses_path
  end

  def edit
    @klass = Klass.find(params[:id])
  end

  def create
    @klass = Klass.new(klass_params)
    if @klass.save
      redirect_to klasses_path
    else
      render :new
    end
  end

  def destroy
    @klass = Klass.find(params[:id])
    @klass.destroy!
    redirect_to klasses_path
  end

private
  def klass_params
    params.require(:klass).permit(:name)
  end
end

app/helpers/klasses_helper.rb
# == Schema Information
#
# Table name: klasses
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module KlassesHelper
end

app/views/klasses/edit.html.erb
<div class="container">
<h1>Update Class Name</h1>
<%= simple_form_for @klass do |f| %>
<%= f.input :name %>
<%= f.submit "Confirm Changes", class: "btn btn-primary" %>
<%= link_to "Cancel", :back, class: "btn btn-primary" %>
<% end %>

</div>

app/views/klasses/index.html.erb
<div class="container">
  <h1>Class</h1>
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Class Name</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @klasses.each do |klass| %>
      <tr>
        <td><%= link_to klass.name, klass_standards_path(klass_id: klass.id) %></td>
        <td><%= link_to "Edit", edit_klass_path(klass), class: "btn btn-default" %></td>
        <td><%= link_to "Delete", klass_path(klass), class: "btn btn-default", method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Add New House", new_klass_path, class: "btn btn-primary" %>
</div>

app/views/klasses/new.html.erb
<div class="container">
  <h1>Add New House</h1>
  <%= simple_form_for @klass do |f| %>
  <%= f.input :name, required: true %>
  <%= f.submit "Add House", class: "btn btn-primary" %>
  <%= link_to "Cancel", klasses_path, class: "btn btn-primary" %>
  <% end %>
</div>